# Generated by Django 6.0.6 on 2026-07-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendingSalesImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('records', models.JSONField()),
                ('source_files', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '대기 중 업로드',
                'unique_together': {('session_key', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True, verbose_name='연도')),
                ('month', models.PositiveSmallIntegerField(db_index=True, verbose_name='월')),
                ('item_code', models.CharField(max_length=64, verbose_name='품목코드')),
                ('item_name', models.CharField(blank=True, max_length=256, verbose_name='품목명')),
                ('voucher_no', models.CharField(db_index=True, max_length=32, verbose_name='전표별')),
                ('item_label', models.CharField(blank=True, max_length=256, verbose_name='품목별')),
                ('customer_name', models.CharField(blank=True, max_length=256, verbose_name='거래처별')),
                ('customer_code', models.CharField(blank=True, max_length=32, verbose_name='거래처코드')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=16, verbose_name='수량')),
                ('supply_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='공급가액')),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='부가세')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='합계')),
                ('memo', models.CharField(blank=True, max_length=512, verbose_name='적요')),
                ('item_category_code', models.CharField(blank=True, max_length=8, verbose_name='품목분류코드')),
                ('item_category_name', models.CharField(max_length=64, verbose_name='품목분류')),
                ('customer_category_code', models.CharField(blank=True, max_length=8, verbose_name='거래처분류코드')),
                ('customer_category_name', models.CharField(max_length=64, verbose_name='거래처분류')),
                ('is_unclassified_item', models.BooleanField(default=False, verbose_name='품목 미분류')),
                ('is_unclassified_customer', models.BooleanField(default=False, verbose_name='거래처 미분류')),
                ('source_file', models.CharField(blank=True, max_length=256, verbose_name='원본파일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '매출 원자료',
                'verbose_name_plural': '매출 원자료',
                'indexes': [models.Index(fields=['year', 'month'], name='sales_analy_year_18f30b_idx'), models.Index(fields=['year', 'month', 'customer_category_code', 'item_category_code'], name='sales_analy_year_1b792a_idx')],
            },
        ),
    ]
