# Generated by Django 6.0.6 on 2026-07-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_analysis', '0003_welfare_output_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingProfitImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('records', models.JSONField()),
                ('period_label', models.CharField(blank=True, max_length=128)),
                ('source_files', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '대기 중 이익 업로드',
            },
        ),
        migrations.CreateModel(
            name='ProfitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_label', models.CharField(blank=True, max_length=64, verbose_name='분류명(원본)')),
                ('item_category_code', models.CharField(blank=True, max_length=8, verbose_name='품목분류코드')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=16, verbose_name='수량')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='금액')),
                ('is_unclassified_item', models.BooleanField(default=False, verbose_name='품목 미분류')),
                ('period_label', models.CharField(blank=True, max_length=128, verbose_name='조회기간(표시용)')),
                ('source_file', models.CharField(blank=True, max_length=256, verbose_name='원본파일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '이익 원자료',
                'verbose_name_plural': '이익 원자료',
                'indexes': [models.Index(fields=['item_category_code'], name='sales_analy_item_ca_edaa9a_idx')],
            },
        ),
    ]
