# Generated by Django 6.0.6 on 2026-07-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_analysis', '0004_profit_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitrecord',
            name='customer_code',
            field=models.CharField(blank=True, max_length=32, verbose_name='거래처코드'),
        ),
        migrations.AddField(
            model_name='profitrecord',
            name='customer_name',
            field=models.CharField(blank=True, max_length=256, verbose_name='거래처명'),
        ),
        migrations.AddField(
            model_name='profitrecord',
            name='item_code',
            field=models.CharField(blank=True, max_length=64, verbose_name='품목코드'),
        ),
        migrations.AddField(
            model_name='profitrecord',
            name='item_name',
            field=models.CharField(blank=True, max_length=256, verbose_name='품목명'),
        ),
        migrations.AlterField(
            model_name='profitrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='이익금액'),
        ),
        migrations.AlterField(
            model_name='profitrecord',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16, verbose_name='판매수량'),
        ),
    ]
