# Generated by Django 6.0.6 on 2026-07-02

from django.db import migrations, models


def backfill_customer_category(apps, schema_editor):
    ProfitRecord = apps.get_model("sales_analysis", "ProfitRecord")
    import re

    pattern = re.compile(r"^([a-zA-Z])", re.ASCII)
    known = {"a", "b", "c", "d", "e", "z"}

    for record in ProfitRecord.objects.all().iterator():
        code = (record.customer_code or "").strip()
        match = pattern.match(code)
        cat = match.group(1).lower() if match else ""
        record.customer_category_code = cat
        record.is_unclassified_customer = cat not in known
        record.save(update_fields=["customer_category_code", "is_unclassified_customer"])


class Migration(migrations.Migration):

    dependencies = [
        ("sales_analysis", "0005_profit_record_detail"),
    ]

    operations = [
        migrations.AddField(
            model_name="profitrecord",
            name="customer_category_code",
            field=models.CharField(blank=True, max_length=8, verbose_name="거래처분류코드"),
        ),
        migrations.AddField(
            model_name="profitrecord",
            name="is_unclassified_customer",
            field=models.BooleanField(default=False, verbose_name="거래처 미분류"),
        ),
        migrations.AddIndex(
            model_name="profitrecord",
            index=models.Index(fields=["customer_category_code"], name="sales_analy_custome_idx"),
        ),
        migrations.RunPython(backfill_customer_category, migrations.RunPython.noop),
    ]
