# Generated by Django 6.0.6 on 2026-07-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_analysis", "0006_profit_customer_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="profitrecord",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name="원가"),
        ),
        migrations.AlterField(
            model_name="profitrecord",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name="이익금"),
        ),
    ]
